tasks:
    - init: cd example && pip install -r requirements.txt && python manage.py migrate
      command: python manage.py runserver

    - init: cd example/client && yarn install
      command: yarn dev

ports:
    - port: 3000 # Vite server (serves compiled JS/CSS files in development)
      visibility: public
    - port: 6006 # Storybook
    - port: 8000 # Example
vscode:
    extensions:
        - ms-python.python
        - esbenp.prettier-vscode
        - dbaeumer.vscode-eslint
