name: Django Bridge CI

on:
  push:
    branches:
      - main
      - "stable/**"

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12"]
        django: ["4.2", "5.0"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          cd python
          tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}
